### ISSUE TITLE
Add [Health_Fund_Working].[dbo].[ELIGIBILITY_STANDARDIZED] table into member Data (Eligibility)

### ISSUE THREAD

**Issue by vkhangulov** [32bjfunds/data-maps#9]
Please add table shell for [Health_Fund_Working].[dbo].[ELIGIBILITY_STANDARDIZED] table into member Data (Eligibility). We will then assign someone to fill out information for individual fields.

**Comment by ougni** [comment]
Available here: https://github.com/32bjfunds/member-data-docs

**Comment by vkhangulov** [comment]
Displays "Page not found"
